* Fancy URLs Menu.

The Fancy URLs Menu (previously Fancy FFAP Menu) provides a way of finding URLs in the current buffer and opening them in a browser of your choosing.

This package was written because of the limitations of the src_elisp{ffap-menu} command of the FFAP package (Find File At Point!  Get your brain out of the gutter!) and uses the src_elisp{ffap-menu-rescan} function to assemble the list of URLs in the current buffer.

It also derives from src_elisp{Tabulated-list-mode}, so it is similar in user experience to src_elisp{list-buffers}, src_elisp{list-processes}, and src_elisp{list-packages}, as all three derive from src_elisp{Tabulated-list-mode}.

** Usage.

Currently only the src_elisp{fancy-urls-menu-list-urls} command works.

** Installation.

*** Manual installation.

First clone and open the package with emacs:

#+begin_src sh
  git clone https://codeberg.org/kakafarm/emacs-fancy-urls-menu/
#+end_src

Now, in Emacs, run the command ~package-install-from-file~ and choose the file =emacs-fancy-urls-menu/fancy-urls-menu.el= in the cloned repository.

** Contribute: Questions, Bug reports, Feature Requests, And Patches.

If you have any questions to ask, bugs to report, or features to suggest, use [[https://codeberg.org/kakafarm/emacs-fancy-ffap-menu/issues/new][the Codeberg issue tracker]].

If you have patches to submit, please send them on [[https://codeberg.org/kakafarm/emacs-fancy-ffap-menu/pulls][the Codeberg pull requests thingamabob]].

** Support.

[[https://buymeacoffee.com/kakafarm][Support me 💰 on "buymeacoffee"]].
